AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: |
  DynamoDB resources for the RealTimeChat application.


Parameters:
  Env:
    Type: String
 
Resources:
  ##########################################################################
  #                       DynamoDB                                         #
  ##########################################################################
  RealTimeChatDynamoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: RealTimeChatTable
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
        - AttributeName: gsi1sk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: GSI1
          KeySchema:
            - AttributeName: pk
              KeyType: HASH
            - AttributeName: gsi1sk
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      TimeToLiveSpecification:
        Enabled: true
        AttributeName: ttl
      BillingMode: PAY_PER_REQUEST
      Tags:
        - Key: Environment
          Value: !Ref Env

Outputs:
  TableName:
    Value: !Ref RealTimeChatDynamoTable
    Description: The name of the DynamoDB table

  TableArn:
    Value: !GetAtt RealTimeChatDynamoTable.Arn
    Description: The ARN of the DynamoDB table
    

