version = 0.1
[default.deploy.parameters]
stack_name = "sam-app"
resolve_s3 = true
s3_prefix = "sam-app"
region = "us-east-1"
profile = "gutkedu-terraform"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "TableName=\"table\""
image_repositories = []
